name: Deploy.To.Yandex

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks
    # that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE,
        # so your job can access it
        - uses: actions/checkout@v3
        
        - name: Deploy Function preachy-amo-to-sheet
          id: sls-func-preachy-amo-to-sheet
          uses: yc-actions/yc-sls-function@v2.5.0
          with:
            yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
            folder-id: 'b1gslim9pjl5jan2tbod'
            function-name: 'preachy-amo-to-sheet'
            runtime: 'dotnetcore31'
            memory: '128Mb'
            entrypoint: 'AmoToSheetFunc.AmoToSheetFunction'
            environment: |
              YA_OBJECT_STORAGE_SECRET_KEY=${{ secrets.YA_OBJECT_STORAGE_SECRET_KEY }}
              AMO_CLIENT_SECRET=${{ secrets.AMO_CLIENT_SECRET }}
            source-root: ./AmoToSheetFunc
            include: "."
            
        - name: Deploy Function update-amo-secrets
          id: sls-func-update-amo-secrets
          uses: yc-actions/yc-sls-function@v2.5.0
          with:
            yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
            folder-id: 'b1gslim9pjl5jan2tbod'
            function-name: 'update-amo-secrets'
            runtime: 'dotnetcore31'
            memory: '128Mb'
            entrypoint: 'AmoKeyUpdateFunc.AmoKeyUpdateFunc'
            environment: |
              YA_OBJECT_STORAGE_SECRET_KEY=${{ secrets.YA_OBJECT_STORAGE_SECRET_KEY }}
              AMO_CLIENT_SECRET=${{ secrets.AMO_CLIENT_SECRET }}
            source-root: ./AmoKeyUpdateFunc
            include: "."
